# Generated by Django 4.1 on 2022-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alter_clockmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
