# Generated by Django 4.1 on 2022-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alter_clockmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockmodel',
            name='date_created',
            field=models.DateField(blank=True, default='%A,%d %B, %Y'),
        ),
    ]
