# Generated by Django 4.1 on 2022-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_alter_clockmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockmodel',
            name='clock',
            field=models.IntegerField(default=0, verbose_name='Відпрацюваних_Годин'),
        ),
        migrations.AlterField(
            model_name='clockmodel',
            name='date_created',
            field=models.DateField(blank=True),
        ),
    ]
