# Generated by Django 4.1 on 2022-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0007_alter_clockmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockmodel',
            name='date_created',
            field=models.DateField(),
        ),
    ]
