# Generated by Django 4.1 on 2022-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0008_alter_clockmodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockmodel',
            name='day',
            field=models.CharField(default=23, max_length=50, verbose_name='День'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clockmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
